### ISSUE TITLE
[Security] Potential Secret Leak

### ISSUE THREAD

**Issue by raima-zachariah** [eachtech-dev/navhub#39]
It has been noticed that while using chromaui/action@v1 your projectToken 546ee9f895b0 is present in plaintext. Please ensure that secrets are encrypted or not passed as plain text in github workflows.

**Comment by yakovlev-alexey** [comment]
Hello! Thank you for your notice. However, as stated in [documentation](https://www.chromatic.com/docs/github-actions#forked-repositories), exposing Chromatic project token is a safe and legitimate way to run Chromatic on PRs from forked repositories.
